// vue-app/src/views/game/BoardGame.vue
<template>
    <div class="board-game-container" :style="{'background-color': styleData.background_color}">
      <div class="board-game-header" :style="{'color': styleData.header_color}">
        <h2 :style="{'font-size': styleData.game_title_font_size}">Jeu de Plateau</h2>
        <router-link to="/characters" class="btn btn-outline-secondary">Retour aux personnages</router-link>
      </div>
      
      <Alert v-if="error" type="danger">{{ error }}</Alert>
      <Alert v-if="success" type="success">{{ success }}</Alert>
      
      <Loading :show="loading" message="Chargement du jeu..." />
      
      <div v-if="!loading && character && boardGame" class="board-game-content" :style="{'color': styleData.text_color, 'font-family': styleData.font_family, 'font-size': styleData.font_size}">
        <div class="character-info">
          <h3>{{ character.name }}</h3>
          <div class="character-stats">
            <div class="stat">
              <span class="stat-name">Santé:</span>
              <span class="stat-value">{{ character.health }}/100</span>
            </div>
            <div class="stat">
              <span class="stat-name">Niveau:</span>
              <span class="stat-value">{{ character.level }}</span>
            </div>
          </div>
        </div>
        
        <!-- Plateau de jeu avec le composant -->
        <BoardGameComponent 
          :board="boardGame.board"
          :current-position="boardGame.current_position"
          :board-length="boardGame.length"
          :disabled="loading || boardGame.is_completed || boardGame.is_game_over"
          @roll="handleRoll"
        />
        
        <!-- Journal de jeu -->
        <div class="game-result" :style="{'color': styleData.text_color}">
          <h3>Déroulement du jeu</h3>
          <pre class="game-log">{{ gameResult }}</pre>
          
          <div class="game-status">
            <div v-if="boardGame.is_completed" class="game-completed">
              <h4>Félicitations !</h4>
              <p>Vous avez terminé le plateau avec succès !</p>
            </div>
            
            <div v-if="boardGame.is_game_over" class="game-over">
              <h4>Game Over</h4>
              <p>Votre personnage est mort durant le jeu.</p>
            </div>
          </div>
        </div>
        
        <div class="game-actions">
          <button 
            class="btn" 
            :style="{'background-color': styleData.button_color, 'color': styleData.text_color}" 
            @click="restartGame"
          >
            Rejouer
          </button>
          <router-link to="/characters" class="btn btn-secondary">Retour aux personnages</router-link>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import { onMounted, ref, computed } from 'vue'
  import { useRouter } from 'vue-router'
  import { useGameStore } from '@/store/game'
  import Alert from '@/components/ui/Alert.vue'
  import Loading from '@/components/ui/Loading.vue'
  import BoardGameComponent from '@/components/game/BoardGame.vue'
  
  export default {
    name: 'BoardGame',
    components: {
      Alert,
      Loading,
      BoardGameComponent
    },
    setup() {
      const router = useRouter()
      const gameStore = useGameStore()
      
      const error = ref('')
      const success = ref('')
      const loading = ref(false)
      const styleData = ref(getDefaultStyleData())
      
      // Démarrer le jeu
      const startGame = async () => {
        loading.value = true
        error.value = ''
        
        try {
          const result = await gameStore.startBoardGame()
          
          if (result.success) {
            success.value = 'Jeu de plateau chargé avec succès'
            
            // Effacer le message après un court délai
            setTimeout(() => {
              success.value = ''
            }, 2000)
          } else {
            error.value = result.message || 'Erreur lors du chargement du jeu de plateau'
            
            // Si le problème est lié au personnage actif, rediriger vers la liste des personnages
            if (result.message && result.message.includes('personnage actif')) {
              setTimeout(() => {
                router.push('/characters')
              }, 2000)
            }
          }
        } catch (err) {
          error.value = 'Une erreur est survenue lors du chargement du jeu'
          console.error(err)
        } finally {
          loading.value = false
        }
      }
      
      // Gérer le lancer de dé et le déplacement
      const handleRoll = async (diceValue) => {
        if (loading.value || !gameStore.boardGame) return
        
        loading.value = true
        error.value = ''
        
        try {
          const result = await gameStore.playBoardGameTurn(`forward_${diceValue}`)
          
          if (result.success) {
            // Si le joueur a monté de niveau, afficher un message
            if (result.level_up) {
              success.value = 'Vous avez gagné un niveau !'
              
              // Effacer le message après un court délai
              setTimeout(() => {
                success.value = ''
              }, 3000)
            }
          } else {
            error.value = result.message || 'Erreur lors du tour de jeu'
          }
        } catch (err) {
          error.value = 'Une erreur est survenue lors du tour de jeu'
          console.error(err)
        } finally {
          loading.value = false
        }
      }
      
      // Redémarrer le jeu
      const restartGame = () => {
        gameStore.resetGameStates()
        startGame()
      }
      
      // Styles par défaut
      const getDefaultStyleData = () => {
        return {
          "background_color": "#282c34",
          "header_color": "#61dafb",
          "button_color": "#ff5733",
          "text_color": "#ffffff",
          "font_family": "Arial, sans-serif",
          "font_size": "16px",
          "board_border": "2px solid #61dafb",
          "game_title_font_size": "2rem"
        }
      }
      
      onMounted(() => {
        startGame()
      })
      
      return {
        character: computed(() => gameStore.character),
        boardGame: computed(() => gameStore.boardGame),
        gameResult: computed(() => gameStore.gameResult),
        styleData,
        error,
        success,
        loading,
        handleRoll,
        restartGame
      }
    }
  }
  </script>
  
  <style lang="scss" scoped>
  .board-game-container {
    min-height: calc(100vh - 150px);
    padding: 20px;
    transition: background-color 0.3s ease;
  }
  
  .board-game-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
    
    h2 {
      margin: 0;
    }
  }
  
  .board-game-content {
    max-width: 1000px;
    margin: 0 auto;
  }
  
  .character-info {
    background-color: rgba(255, 255, 255, 0.1);
    border-radius: 8px;
    padding: 15px;
    margin-bottom: 20px;
    
    h3 {
      margin-top: 0;
      margin-bottom: 10px;
    }
    
    .character-stats {
      display: flex;
      gap: 20px;
      
      .stat {
        .stat-name {
          font-weight: 600;
          margin-right: 5px;
        }
      }
    }
  }
  
  .game-result {
    margin-top: 30px;
    
    h3 {
      margin-bottom: 15px;
    }
    
    .game-log {
      padding: 15px;
      background-color: rgba(255, 255, 255, 0.1);
      border-radius: 8px;
      font-family: monospace;
      overflow-y: auto;
      max-height: 300px;
      white-space: pre-wrap;
    }
    
    .game-status {
      margin-top: 20px;
      text-align: center;
      
      h4 {
        font-size: 1.5rem;
        margin-bottom: 10px;
      }
      
      .game-completed {
        color: #28a745;
      }
      
      .game-over {
        color: #dc3545;
      }
    }
  }
  
  .game-actions {
    margin-top: 30px;
    display: flex;
    justify-content: center;
    gap: 20px;
    
    button, a {
      min-width: 120px;
    }
  }
  
  @media (max-width: 768px) {
    .board-game-header {
      flex-direction: column;
      gap: 10px;
      align-items: flex-start;
    }
    
    .character-stats {
      flex-direction: column;
      gap: 5px !important;
    }
    
    .game-actions {
      flex-direction: column;
      align-items: center;
      
      button, a {
        width: 100%;
      }
    }
  }
  </style>

// angular-app/src/app/features/game/board-game/board-game.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { GameService } from '../../../core/services/game.service';
import { CharacterService } from '../../../core/services/character.service';
import { Character } from '../../../core/models/character.model';

@Component({
  selector: 'app-board-game',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './board-game.component.html',
  styleUrls: ['./board-game.component.scss']
})
export class BoardGameComponent implements OnInit {
  gameResult: any = null;
  loading: boolean = false;
  errorMessage: string = '';
  successMessage: string = '';
  character: Character | null = null;
  styleData: any = {};
  plateauGame: any = null;
  gameState: any = null;
  currentDirection: string = '';

  constructor(
    private gameService: GameService,
    private characterService: CharacterService,
    private router: Router
  ) {}

  ngOnInit(): void {
    // Vérifier si un personnage est sélectionné
    this.character = this.characterService.getActiveCharacter();
    
    if (!this.character) {
      this.errorMessage = 'Vous devez sélectionner un personnage pour accéder au jeu de plateau';
      setTimeout(() => {
        this.router.navigate(['/characters']);
      }, 2000);
      return;
    }
    
    this.startGame();
  }

  startGame(): void {
    this.loading = true;
    this.errorMessage = '';
    
    this.gameService.startBoardGame().subscribe({
      next: (data) => {
        if (data.success) {
          this.gameResult = data.game_result || '';
          // Si le backend renvoie un personnage, utiliser ses infos
          if (data.character) {
            // Mettre à jour localement avec les données du serveur
            this.character = {
              ...this.character!,  // Conserver les données locales
              ...data.character    // Mais mettre à jour avec les données du serveur
            };
          }
          this.styleData = data.style_data || this.getDefaultStyleData();
          this.plateauGame = data.game_state || data.tableau_game;
          this.gameState = data.game_state;
          this.successMessage = 'Jeu de plateau chargé avec succès!';
        } else {
          this.errorMessage = data.message || 'Erreur lors du chargement du jeu de plateau';
          
          // Si le problème est lié au personnage actif, tenter de le gérer
          if (data.message && data.message.includes('personnage actif')) {
            this.errorMessage = 'Veuillez sélectionner un personnage dans la liste des personnages';
            setTimeout(() => {
              this.router.navigate(['/characters']);
            }, 2000);
          }
        }
        this.loading = false;
      },
      error: (error) => {
        this.errorMessage = error.error?.message || 'Erreur lors du chargement du jeu de plateau';
        this.loading = false;
        
        // Gestion spécifique de l'erreur d'absence de personnage actif
        if (error.error?.message && error.error.message.includes('personnage actif')) {
          this.errorMessage = 'Veuillez sélectionner un personnage dans la liste des personnages';
          setTimeout(() => {
            this.router.navigate(['/characters']);
          }, 2000);
        }
      }
    });
  }

  // Méthode pour lancer le dé et se déplacer
  rollDiceAndMove(): void {
    // Simuler un lancer de dé (1 à 6)
    const diceValue = Math.floor(Math.random() * 6) + 1;
    this.playTurn('forward_' + diceValue); // Par exemple, "forward_3" pour avancer de 3 cases
  }

  // Méthode pour choisir une direction (si le jeu le permet)
  chooseDirection(direction: string): void {
    this.playTurn(direction); // Par exemple, "left", "right", "up", "down"
  }

  playTurn(direction: string): void {
    if (!this.character) {
      this.errorMessage = 'Vous devez sélectionner un personnage pour jouer';
      return;
    }

    this.loading = true;
    this.currentDirection = direction;
    
    this.gameService.playBoardGameTurn(direction).subscribe({
      next: (data) => {
        if (data.success) {
          this.gameResult = (this.gameResult || '') + '\n' + (data.turn_result || '');
          this.plateauGame = data.game_state;
          this.gameState = data.game_state;
          
          // Mise à jour du personnage si le backend le renvoie
          if (data.character) {
            this.character = {
              ...this.character!,
              ...data.character
            };
          }
        } else {
          this.errorMessage = data.message || 'Erreur lors du jeu';
        }
        this.loading = false;
      },
      error: (error) => {
        this.errorMessage = error.error?.message || 'Erreur lors du jeu';
        this.loading = false;
      }
    });
  }

  // Styles par défaut si le backend n'en fournit pas
  getDefaultStyleData(): any {
    return {
      "background_color": "#282c34",
      "header_color": "#61dafb",
      "button_color": "#ff5733",
      "text_color": "#ffffff",
      "font_family": "Arial, sans-serif",
      "font_size": "16px",
      "board_border": "2px solid #61dafb",
      "game_title_font_size": "2rem"
    };
  }
}
<div class="board-game-container" [ngStyle]="{'background-color': styleData.background_color}">
  <div class="board-game-header" [ngStyle]="{'color': styleData.header_color}">
    <h2 [ngStyle]="{'font-size': styleData.game_title_font_size}">Jeu de Plateau</h2>
    <a routerLink="/characters" class="btn btn-outline-secondary">Retour aux personnages</a>
  </div>
  
  <div *ngIf="errorMessage" class="alert alert-danger">
    {{ errorMessage }}
  </div>
  
  <div *ngIf="successMessage" class="alert alert-success">
    {{ successMessage }}
  </div>
  
  <div *ngIf="loading" class="loading-spinner">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Chargement...</span>
    </div>
  </div>
  
  <div *ngIf="!loading && character && plateauGame" class="board-game-content" [ngStyle]="{'color': styleData.text_color, 'font-family': styleData.font_family, 'font-size': styleData.font_size}">
    <div class="character-info">
      <h3>{{ character.name }}</h3>
      <div class="character-stats">
        <div class="stat">
          <span class="stat-name">Santé:</span>
          <span class="stat-value">{{ character.health }}/100</span>
        </div>
        <div class="stat">
          <span class="stat-name">Niveau:</span>
          <span class="stat-value">{{ character.level }}</span>
        </div>
      </div>
    </div>
    
    <!-- Ajout des contrôles pour lancer le dé -->
    <div class="game-controls">
      <button class="btn btn-success" (click)="rollDiceAndMove()" [disabled]="loading">
        <i class="bi bi-dice-6"></i> Lancer le dé
      </button>
      
      <!-- Boutons de direction (si applicables dans votre jeu) -->
      <div class="direction-controls" *ngIf="plateauGame.allow_directional_move">
        <button class="btn btn-primary direction-btn" (click)="chooseDirection('up')" [disabled]="loading">
          <i class="bi bi-arrow-up"></i>
        </button>
        <div class="middle-row">
          <button class="btn btn-primary direction-btn" (click)="chooseDirection('left')" [disabled]="loading">
            <i class="bi bi-arrow-left"></i>
          </button>
          <button class="btn btn-primary direction-btn" (click)="chooseDirection('right')" [disabled]="loading">
            <i class="bi bi-arrow-right"></i>
          </button>
        </div>
        <button class="btn btn-primary direction-btn" (click)="chooseDirection('down')" [disabled]="loading">
          <i class="bi bi-arrow-down"></i>
        </button>
      </div>
    </div>
    
    <!-- Plateau de jeu -->
    <div class="game-board" [ngStyle]="{'border': styleData.board_border}">
      <div class="board-cells">
        <div *ngFor="let cell of plateauGame.board; let i = index" class="board-cell" 
             [ngClass]="{
               'cell-current': i === plateauGame.current_position,
               'cell-empty': cell === null,
               'cell-item': cell && cell.type,
               'cell-enemy': cell && cell.name
             }">
          {{ i + 1 }}
          <div class="cell-content" *ngIf="cell">
            <span *ngIf="cell.type">{{ cell.name }}</span>
            <span *ngIf="cell.health">{{ cell.name }}</span>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Journal de jeu -->
    <div class="game-result" [ngStyle]="{'color': styleData.text_color}">
      <h3>Déroulement du jeu</h3>
      <pre class="game-log">{{ gameResult }}</pre>
      
      <div class="game-status">
        <div *ngIf="plateauGame.is_completed" class="game-completed">
          <h4>Félicitations !</h4>
          <p>Vous avez terminé le plateau avec succès !</p>
        </div>
        
        <div *ngIf="plateauGame.is_game_over" class="game-over">
          <h4>Game Over</h4>
          <p>Votre personnage est mort durant le jeu.</p>
        </div>
      </div>
    </div>
    
    <div class="game-actions">
      <button class="btn" [ngStyle]="{'background-color': styleData.button_color, 'color': styleData.text_color}" (click)="startGame()">Rejouer</button>
      <a routerLink="/characters" class="btn btn-secondary">Retour aux personnages</a>
    </div>
  </div>
</div>
