// angular-app/src/app/features/inventory/inventory-list/inventory-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { InventoryService } from '../../../core/services/inventory.service';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-inventory-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './inventory-list.component.html',
  styleUrls: ['./inventory-list.component.scss']
})
export class InventoryListComponent implements OnInit {
  items: any[] = [];
  loading: boolean = false;
  errorMessage: string = '';
  sortBy: string = 'name';
  order: string = 'asc';
  characterName: string = '';
  
  constructor(
    private inventoryService: InventoryService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.loadInventory();
  }

  loadInventory(): void {
    this.loading = true;
    this.inventoryService.getInventory(this.sortBy, this.order).subscribe({
      next: (response: any) => {
        if (response.success) {
          this.items = response.items || [];
          this.characterName = response.character_name || '';
        } else {
          this.errorMessage = response.message || 'Erreur lors du chargement de l\'inventaire';
        }
        this.loading = false;
      },
      error: (error) => {
        this.errorMessage = error.error?.message || 'Erreur lors du chargement de l\'inventaire';
        this.loading = false;
      }
    });
  }

  sortInventory(column: string): void {
    if (this.sortBy === column) {
      this.order = this.order === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortBy = column;
      this.order = 'asc';
    }
    this.loadInventory();
  }

  deleteItem(itemId: number): void {
    if (confirm('Êtes-vous sûr de vouloir supprimer cet objet ?')) {
      this.inventoryService.deleteItem(itemId).subscribe({
        next: (response) => {
          if (response.success) {
            this.loadInventory();
          } else {
            this.errorMessage = response.message || 'Erreur lors de la suppression de l\'objet';
          }
        },
        error: (error) => {
          this.errorMessage = error.error?.message || 'Erreur lors de la suppression de l\'objet';
        }
      });
    }
  }

  consumeItem(itemId: number): void {
    this.inventoryService.consumeItem(itemId).subscribe({
      next: (response) => {
        if (response.success) {
          this.loadInventory();
        } else {
          this.errorMessage = response.message || 'Erreur lors de la consommation de l\'objet';
        }
      },
      error: (error) => {
        this.errorMessage = error.error?.message || 'Erreur lors de la consommation de l\'objet';
      }
    });
  }

  getItemTypeClass(typeName: string | undefined): string {
    if (!typeName) return 'badge-secondary';
    
    switch (typeName.toLowerCase()) {
      case 'potion':
        return 'badge-success';
      case 'arme':
      case 'weapon':
        return 'badge-danger';
      case 'armure':
      case 'armor':
        return 'badge-info';
      case 'plante':
        return 'badge-warning';
      default:
        return 'badge-secondary';
    }
  }

  isConsumable(typeName: string | undefined): boolean {
    if (!typeName) return false;
    return ['potion', 'plante'].includes(typeName.toLowerCase());
  }
}
<!-- src/app/features/inventory/inventory-list/inventory-list.component.html -->
<div class="inventory-container">
  <div class="inventory-header">
    <h2>Inventaire de {{ characterName }}</h2>
    <button class="btn btn-primary" routerLink="/inventory/add">Ajouter un objet</button>
  </div>
  
  <div *ngIf="errorMessage" class="alert alert-danger">
    {{ errorMessage }}
  </div>
  
  <div *ngIf="loading" class="loading-spinner">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Chargement...</span>
    </div>
  </div>
  
  <div *ngIf="!loading && items.length === 0" class="no-items">
    <p>Vous n'avez pas encore d'objets dans votre inventaire.</p>
    <button class="btn btn-primary" routerLink="/inventory/add">Ajouter un objet</button>
  </div>
  
  <div *ngIf="!loading && items.length > 0" class="inventory-table-container">
    <table class="inventory-table">
      <thead>
        <tr>
          <th (click)="sortInventory('item_name')">
            Nom
            <i class="bi" [ngClass]="sortBy === 'item_name' ? (order === 'asc' ? 'bi-sort-alpha-down' : 'bi-sort-alpha-up') : 'bi-sort'"></i>
          </th>
          <th (click)="sortInventory('item_type')">
            Type
            <i class="bi" [ngClass]="sortBy === 'item_type' ? (order === 'asc' ? 'bi-sort-alpha-down' : 'bi-sort-alpha-up') : 'bi-sort'"></i>
          </th>
          <th (click)="sortInventory('item_quantity')">
            Quantité
            <i class="bi" [ngClass]="sortBy === 'item_quantity' ? (order === 'asc' ? 'bi-sort-numeric-down' : 'bi-sort-numeric-up') : 'bi-sort'"></i>
          </th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let item of items">
          <td>{{ item.name }}</td>
          <td>
            <span class="badge" [ngClass]="getItemTypeClass(item.type_name)">
              {{ item.type_name }}
            </span>
          </td>
          <td>{{ item.quantity }}</td>
          <td class="item-actions">
            <button *ngIf="isConsumable(item.type_name)" class="btn btn-success btn-sm" (click)="consumeItem(item.id)">
              <i class="bi bi-cup-hot"></i> Utiliser
            </button>
            <button class="btn btn-info btn-sm" [routerLink]="['/inventory/edit', item.id]">
              <i class="bi bi-pencil"></i> Modifier
            </button>
            <button class="btn btn-danger btn-sm" (click)="deleteItem(item.id)">
              <i class="bi bi-trash"></i> Supprimer
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// react-app/src/components/inventory/InventoryList.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';

function InventoryList() {
  const [items, setItems] = useState([]);
  const [characterName, setCharacterName] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [sortBy, setSortBy] = useState('item_name');
  const [order, setOrder] = useState('asc');
  const navigate = useNavigate();

  useEffect(() => {
    fetchInventory();
  }, [sortBy, order]);

  const fetchInventory = async () => {
    try {
      const response = await api.get(`/inventory?sort_by=${sortBy}&order=${order}`);
      setItems(response.data.items || []);
      setCharacterName(response.data.character_name || 'Personnage');
      setError('');
    } catch (err) {
      console.error('Error fetching inventory:', err);
      setError('Impossible de récupérer votre inventaire.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleSort = (column) => {
    if (column === sortBy) {
      // Toggle order if clicking the same column
      setOrder(order === 'asc' ? 'desc' : 'asc');
    } else {
      // Default to ascending order for a new column
      setSortBy(column);
      setOrder('asc');
    }
  };

  const deleteItem = async (itemId) => {
    if (!window.confirm('Êtes-vous sûr de vouloir supprimer cet objet ?')) {
      return;
    }

    try {
      await api.post(`/delete/${itemId}`);
      // Refresh the inventory list
      fetchInventory();
    } catch (err) {
      console.error('Error deleting item:', err);
      setError('Erreur lors de la suppression de l\'objet.');
    }
  };

  const consumeItem = async (itemId, itemType) => {
    try {
      const response = await api.post(`/consume/${itemId}`);
      // Refresh the inventory list
      fetchInventory();
      // Show success message
      alert(`Objet consommé ! ${
        itemType === 'potion' 
          ? 'Vous avez récupéré 20 points de vie!' 
          : 'Votre attaque a augmenté de 5 points!'
      }`);
    } catch (err) {
      console.error('Error consuming item:', err);
      setError('Erreur lors de la consommation de l\'objet.');
    }
  };

  if (isLoading) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="inventory-container">
      <h2>Inventaire de {characterName}</h2>
      
      <div className="mb-3">
        <button 
          className="btn btn-success" 
          onClick={() => navigate('/add-item')}
        >
          Ajouter un objet
        </button>
      </div>
      
      {error && <div className="alert alert-danger">{error}</div>}
      
      {items.length === 0 ? (
        <div className="alert alert-info">
          Votre inventaire est vide. Ajoutez des objets ou partez à l'aventure pour en trouver!
        </div>
      ) : (
        <div className="table-responsive">
          <table className="table table-hover">
            <thead>
              <tr>
                <th onClick={() => handleSort('item_name')} style={{ cursor: 'pointer' }}>
                  Nom {sortBy === 'item_name' && (order === 'asc' ? '↑' : '↓')}
                </th>
                <th onClick={() => handleSort('item_type')} style={{ cursor: 'pointer' }}>
                  Type {sortBy === 'item_type' && (order === 'asc' ? '↑' : '↓')}
                </th>
                <th onClick={() => handleSort('item_quantity')} style={{ cursor: 'pointer' }}>
                  Quantité {sortBy === 'item_quantity' && (order === 'asc' ? '↑' : '↓')}
                </th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {items.map(item => (
                <tr key={item.item_id}>
                  <td>{item.item_name}</td>
                  <td>{item.item_type}</td>
                  <td>{item.item_quantity}</td>
                  <td>
                    <div className="btn-group btn-group-sm">
                      <button 
                        className="btn btn-primary"
                        onClick={() => navigate(`/edit-item/${item.item_id}`)}
                      >
                        Modifier
                      </button>
                      
                      {(item.item_type === 'potion' || item.item_type === 'plante') && (
                        <button 
                          className="btn btn-success"
                          onClick={() => consumeItem(item.item_id, item.item_type)}
                        >
                          Utiliser
                        </button>
                      )}
                      
                      <button 
                        className="btn btn-danger"
                        onClick={() => deleteItem(item.item_id)}
                      >
                        Supprimer
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

export default InventoryList;
