// react-app/src/pages/CharacterList.js
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { getCharacters, selectCharacter } from '../api/apiService';

const CharacterList = () => {
  const [characters, setCharacters] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeCharacterId, setActiveCharacterId] = useState(null);
  
  const navigate = useNavigate();

  useEffect(() => {
    const fetchCharacters = async () => {
      try {
        const data = await getCharacters();
        if (data.success) {
          setCharacters(data.characters);
          setActiveCharacterId(data.active_character_id);
        } else {
          setError(data.message);
        }
      } catch (err) {
        setError('Erreur lors du chargement des personnages');
      } finally {
        setLoading(false);
      }
    };

    fetchCharacters();
  }, []);

  const handleSelectCharacter = async (characterId) => {
    try {
      const data = await selectCharacter(characterId);
      if (data.success) {
        setActiveCharacterId(characterId);
        // Mettre à jour la liste pour refléter le personnage actif
        setCharacters(characters.map(char => ({
          ...char,
          is_active: char.id === characterId
        })));
      } else {
        setError(data.message);
      }
    } catch (err) {
      setError('Erreur lors de la sélection du personnage');
    }
  };

  if (loading) {
    return <div className="text-center py-10">Chargement...</div>;
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">Mes Personnages</h1>
        <Link to="/create-character" className="btn btn-primary">
          Créer un nouveau personnage
        </Link>
      </div>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          {error}
        </div>
      )}

      {characters.length === 0 ? (
        <div className="text-center py-10">
          <p className="text-lg text-gray-600 mb-4">Vous n'avez pas encore de personnages.</p>
          <Link to="/create-character" className="btn btn-primary">
            Créer votre premier personnage
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {characters.map((character) => (
            <div 
              key={character.id}
              className={`card hover:shadow-lg transition-shadow ${
                character.id === activeCharacterId ? 'border-2 border-accent' : ''
              }`}
            >
              <div className="flex justify-between items-start">
                <h2 className="text-xl font-bold">{character.name}</h2>
                {character.id === activeCharacterId && (
                  <span className="bg-accent text-white px-2 py-1 rounded text-xs">Actif</span>
                )}
              </div>
              
              <div className="mt-2">
                <p className="text-gray-600"><span className="font-semibold">Race:</span> {character.race}</p>
                <p className="text-gray-600"><span className="font-semibold">Classe:</span> {character.class}</p>
                <p className="text-gray-600"><span className="font-semibold">Niveau:</span> {character.level}</p>
              </div>
              
              <div className="mt-4">
                <div className="flex items-center">
                  <span className="text-sm font-medium text-gray-700">PV: {character.health}</span>
                  <div className="w-full bg-gray-200 rounded-full h-2.5 ml-2">
                    <div className="bg-green-600 h-2.5 rounded-full" style={{ width: `${character.health}%` }}></div>
                  </div>
                </div>
                
                <div className="grid grid-cols-2 gap-2 mt-2">
                  <div>
                    <p className="text-sm font-medium text-gray-700">Attaque: {character.attack}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-700">Défense: {character.defense}</p>
                  </div>
                </div>
              </div>
              
              <div className="mt-4 grid grid-cols-2 gap-2">
                <button
                  className={`btn ${character.id === activeCharacterId ? 'bg-gray-400 cursor-not-allowed' : 'btn-primary'}`}
                  onClick={() => handleSelectCharacter(character.id)}
                  disabled={character.id === activeCharacterId}
                >
                  {character.id === activeCharacterId ? 'Sélectionné' : 'Sélectionner'}
                </button>
                
                <Link 
                  to="/character-profile"
                  className="btn bg-gray-600 hover:bg-gray-700 text-center"
                  onClick={() => {
                    if (character.id !== activeCharacterId) {
                      handleSelectCharacter(character.id);
                    }
                  }}
                >
                  Détails
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default CharacterList;

// vue-app/src/views/characters/CharacterList.vue
<template>
    <div class="characters-container">
      <div class="characters-header">
        <h2>Mes Personnages</h2>
        <router-link to="/characters/create" class="btn btn-primary">Créer un nouveau personnage</router-link>
      </div>
      
      <Alert v-if="error" type="danger">{{ error }}</Alert>
      <Alert v-if="success" type="success">{{ success }}</Alert>
      
      <Loading :show="loading" message="Chargement des personnages..." />
      
      <div v-if="!loading && characters.length === 0" class="no-characters">
        <p>Vous n'avez pas encore de personnage.</p>
        <router-link to="/characters/create" class="btn btn-primary">Créer un personnage</router-link>
      </div>
      
      <div v-if="!loading && characters.length > 0" class="character-list">
        <CharacterCard 
          v-for="character in characters" 
          :key="character.id" 
          :character="character" 
        >
          <template #actions>
            <button 
              class="btn" 
              :class="{'btn-primary': !character.is_active, 'btn-success': character.is_active}"
              :disabled="character.is_active"
              @click="selectCharacter(character.id)"
            >
              {{ character.is_active ? 'Personnage actif' : 'Sélectionner' }}
            </button>
            <router-link :to="`/character/${character.id}`" class="btn btn-outline-secondary">Détails</router-link>
          </template>
        </CharacterCard>
      </div>
      
      <!-- Section Mode de Jeu - Visible uniquement quand un personnage est sélectionné -->
      <div v-if="hasSelectedCharacter" class="game-modes-section">
        <h3>Modes de jeu</h3>
        <div class="game-modes-container">
          <div class="game-mode-card">
            <div class="mode-icon">
              <i class="bi bi-journal-text"></i>
            </div>
            <h4>Quêtes</h4>
            <p>Partez à l'aventure et relevez des défis pour gagner de l'expérience.</p>
            <router-link to="/game/quests" class="btn btn-primary">Jouer aux quêtes</router-link>
          </div>
          
          <div class="game-mode-card">
            <div class="mode-icon">
              <i class="bi bi-dice-6"></i>
            </div>
            <h4>Plateau de jeu</h4>
            <p>Avancez sur le plateau, lancez les dés et découvrez ce qui vous attend.</p>
            <router-link to="/game/board" class="btn btn-primary">Jouer au plateau</router-link>
          </div>
          
          <div class="game-mode-card">
            <div class="mode-icon">
              <i class="bi bi-lightning-charge"></i>
            </div>
            <h4>Mode Versus</h4>
            <p>Affrontez d'autres personnages dans des combats impitoyables.</p>
            <router-link to="/game/versus" class="btn btn-primary">Jouer en versus</router-link>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import { onMounted, ref, computed } from 'vue'
  import { useCharacterStore } from '@/store/character'
  import Alert from '@/components/ui/Alert.vue'
  import Loading from '@/components/ui/Loading.vue'
  import CharacterCard from '@/components/game/CharacterCard.vue'
  
  export default {
    name: 'CharacterList',
    components: {
      Alert,
      Loading,
      CharacterCard
    },
    setup() {
      const characterStore = useCharacterStore()
      
      const loading = ref(false)
      const error = ref('')
      const success = ref('')
      
      const loadCharacters = async () => {
        loading.value = true
        try {
          await characterStore.fetchAllCharacters()
          if (characterStore.error) {
            error.value = characterStore.error
          }
        } catch (err) {
          error.value = 'Une erreur est survenue lors du chargement des personnages'
          console.error(err)
        } finally {
          loading.value = false
        }
      }
      
      const selectCharacter = async (characterId) => {
        loading.value = true
        error.value = ''
        
        try {
          const result = await characterStore.selectCharacter(characterId)
          
          if (result.success) {
            success.value = 'Personnage sélectionné avec succès'
            
            // Effacer le message après un court délai
            setTimeout(() => {
              success.value = ''
            }, 3000)
          } else {
            error.value = result.message || 'Erreur lors de la sélection du personnage'
          }
        } catch (err) {
          error.value = 'Une erreur est survenue lors de la sélection du personnage'
          console.error(err)
        } finally {
          loading.value = false
        }
      }
      
      onMounted(() => {
        loadCharacters()
      })
      
      return {
        characters: computed(() => characterStore.characters),
        hasSelectedCharacter: computed(() => characterStore.hasSelectedCharacter),
        loading,
        error,
        success,
        selectCharacter
      }
    }
  }
  </script>
  
  <style lang="scss" scoped>
  .characters-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
  }
  
  .characters-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }
  
  .no-characters {
    text-align: center;
    padding: 30px;
    background-color: #f8f9fa;
    border-radius: 8px;
  }
  
  .character-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
  }
  
  .game-modes-section {
    margin-top: 30px;
    padding-top: 20px;
    border-top: 1px solid #dee2e6;
    
    h3 {
      text-align: center;
      margin-bottom: 20px;
    }
  }
  
  .game-modes-container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
  }
  
  .game-mode-card {
    background-color: #fff;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    padding: 20px;
    text-align: center;
    
    &:hover {
      transform: translateY(-5px);
      box-shadow: 0 8px 15px rgba(0, 0, 0, 0.2);
    }
    
    .mode-icon {
      font-size: 2rem;
      margin-bottom: 15px;
      color: #007bff;
    }
    
    h4 {
      margin-bottom: 10px;
    }
    
    p {
      margin-bottom: 15px;
      color: #6c757d;
    }
  }
  
  @media (max-width: 768px) {
    .characters-header {
      flex-direction: column;
      gap: 10px;
      align-items: flex-start;
    }
    
    .character-list {
      grid-template-columns: 1fr;
    }
    
    .game-modes-container {
      grid-template-columns: 1fr;
    }
  }
  </style>
