// angular-app/src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  loginForm: FormGroup;
  errorMessage: string = '';
  successMessage: string = '';
  loading: boolean = false;

  constructor(
    private fb: FormBuilder, 
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required]
    });
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    this.loading = true;
    this.errorMessage = '';
    this.successMessage = '';

    const email = this.loginForm.value.email;
    const password = this.loginForm.value.password;

    this.authService.login(email, password).subscribe({
      next: (response) => {
        if (response && response.token) {
          this.successMessage = 'Connexion réussie. Redirection...';
          
          // Redirection après un petit délai pour montrer le message de succès
          setTimeout(() => {
            this.router.navigate(['/characters']);
          }, 1000);
        } else {
          this.errorMessage = response.message || 'Erreur de connexion';
          this.loading = false;
        }
      },
      error: (error) => {
        console.error('Erreur de connexion:', error);
        this.errorMessage = error.error?.message || 'Email ou mot de passe incorrect !';
        this.loading = false;
      }
    });
  }
}
<div class="login-container">
  <div class="login-card">
    <h2>Connexion</h2>
    
    <div *ngIf="errorMessage" class="alert alert-danger">
      {{ errorMessage }}
    </div>
    
    <div *ngIf="successMessage" class="alert alert-success">
      {{ successMessage }}
    </div>
    
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email">Email</label>
        <input 
          type="email" 
          id="email" 
          formControlName="email" 
          class="form-control" 
          [ngClass]="{'is-invalid': loginForm.controls['email'].touched && loginForm.controls['email'].invalid}"
        >
        <div *ngIf="loginForm.controls['email'].touched && loginForm.controls['email'].invalid" class="invalid-feedback">
          <div *ngIf="loginForm.controls['email'].errors?.['required']">L'email est requis</div>
          <div *ngIf="loginForm.controls['email'].errors?.['email']">L'email n'est pas valide</div>
        </div>
      </div>
      
      <div class="form-group">
        <label for="password">Mot de passe</label>
        <input 
          type="password" 
          id="password" 
          formControlName="password" 
          class="form-control"
          [ngClass]="{'is-invalid': loginForm.controls['password'].touched && loginForm.controls['password'].invalid}"
        >
        <div *ngIf="loginForm.controls['password'].touched && loginForm.controls['password'].invalid" class="invalid-feedback">
          <div *ngIf="loginForm.controls['password'].errors?.['required']">Le mot de passe est requis</div>
        </div>
      </div>
      
      <div class="form-actions">
        <button type="submit" class="btn btn-primary" [disabled]="loginForm.invalid || loading">
          <span *ngIf="loading" class="spinner-border spinner-border-sm me-1"></span>
          Se connecter
        </button>
        <p class="mt-3">
          Pas encore de compte ? <a [routerLink]="['/register']">S'inscrire</a>
        </p>
      </div>
    </form>
  </div>
</div>

// react-app/src/components/auth/Login.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';

function Login({ setIsAuthenticated }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);
    
    try {
      const formData = new FormData();
      formData.append('email', email);
      formData.append('password', password);
      
      const response = await api.post('/login', formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      });
      
      // Store token if your backend returns one
      if (response.data.token) {
        localStorage.setItem('token', response.data.token);
      }
      
      setIsAuthenticated(true);
      navigate('/inventory');
    } catch (err) {
      console.error('Login error:', err);
      setError(err.response?.data?.message || 'Email ou mot de passe incorrect !');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="card">
        <div className="card-header bg-primary text-white">
          <h2 className="mb-0">Connexion</h2>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          
          <form onSubmit={handleSubmit}>
            <div className="mb-3">
              <label htmlFor="email" className="form-label">Email</label>
              <input
                type="email"
                className="form-control"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            
            <div className="mb-3">
              <label htmlFor="password" className="form-label">Mot de passe</label>
              <input
                type="password"
                className="form-control"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            
            <button 
              type="submit" 
              className="btn btn-primary w-100"
              disabled={isLoading}
            >
              {isLoading ? 'Connexion...' : 'Se connecter'}
            </button>
          </form>
          
          <div className="mt-3 text-center">
            <p>
              Pas encore de compte ? <a href="/register">S'inscrire</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Login;
