// react-app/src/pages/Login.js
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { login as apiLogin } from '../api/apiService';
import { useAuth } from '../context/AuthContext';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!email || !password) {
      setError('Veuillez remplir tous les champs.');
      return;
    }
    
    setLoading(true);
    setError('');
    
    try {
      const data = await apiLogin(email, password);
      if (data.success) {
        login(data.user);
        navigate('/');
      } else {
        setError(data.message || 'Une erreur est survenue.');
      }
    } catch (err) {
      setError(err.message || 'Une erreur est survenue lors de la connexion.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-800">
      <div className="max-w-md w-full space-y-8 p-8 bg-white dark:bg-primary rounded-lg shadow-md">
        <div className="text-center">
          <h2 className="mt-6 text-3xl font-extrabold text-gray-900 dark:text-white">
            Connexion
          </h2>
        </div>
        
        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative">
            {error}
          </div>
        )}
        
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-200">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="email"
              required
              className="input-field w-full mt-1"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          
          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-200">
              Mot de passe
            </label>
            <input
              id="password"
              name="password"
              type="password"
              required
              className="input-field w-full mt-1"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          
          <div>
            <button
              type="submit"
              disabled={loading}
              className="btn btn-primary w-full"
            >
              {loading ? 'Connexion en cours...' : 'Se connecter'}
            </button>
          </div>
          
          <div className="text-center">
            <p className="text-sm text-gray-600 dark:text-gray-300">
              Pas de compte ? <Link to="/register" className="text-accent hover:underline">S'inscrire</Link>
            </p>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;

// vue-app/src/views/auth/Login.vue
<template>
    <div class="login-container">
      <div class="login-card">
        <h2>Connexion</h2>
        
        <Alert v-if="error" type="danger">{{ error }}</Alert>
        <Alert v-if="success" type="success">{{ success }}</Alert>
        
        <form @submit.prevent="onSubmit">
          <div class="form-group">
            <label for="email">Email</label>
            <input 
              type="email" 
              id="email" 
              v-model="email" 
              class="form-control" 
              :class="{ 'is-invalid': submitted && !email }"
              required
            >
            <div v-if="submitted && !email" class="invalid-feedback">
              L'email est requis
            </div>
          </div>
          
          <div class="form-group">
            <label for="password">Mot de passe</label>
            <input 
              type="password" 
              id="password" 
              v-model="password" 
              class="form-control"
              :class="{ 'is-invalid': submitted && !password }"
              required
            >
            <div v-if="submitted && !password" class="invalid-feedback">
              Le mot de passe est requis
            </div>
          </div>
          
          <div class="form-actions">
            <button type="submit" class="btn btn-primary" :disabled="loading">
              <span v-if="loading" class="spinner-border spinner-border-sm me-1"></span>
              Se connecter
            </button>
            <p class="mt-3">
              Pas encore de compte ? <router-link to="/register">S'inscrire</router-link>
            </p>
          </div>
        </form>
      </div>
    </div>
  </template>
  
  <script>
  import { ref } from 'vue'
  import { useRouter } from 'vue-router'
  import { useAuthStore } from '@/store/auth'
  import Alert from '@/components/ui/Alert.vue'
  
  export default {
    name: 'Login',
    components: {
      Alert
    },
    setup() {
      const router = useRouter()
      const authStore = useAuthStore()
      
      const email = ref('')
      const password = ref('')
      const error = ref('')
      const success = ref('')
      const loading = ref(false)
      const submitted = ref(false)
      
      const onSubmit = async () => {
        submitted.value = true
        
        // Validation basique
        if (!email.value || !password.value) {
          return
        }
        
        loading.value = true
        error.value = ''
        
        try {
          const result = await authStore.login(email.value, password.value)
          
          if (result.success) {
            success.value = 'Connexion réussie. Redirection...'
            
            // Rediriger après un court délai
            setTimeout(() => {
              router.push('/characters')
            }, 1000)
          } else {
            error.value = result.message || 'Erreur de connexion'
          }
        } catch (err) {
          error.value = 'Une erreur est survenue lors de la connexion'
          console.error(err)
        } finally {
          loading.value = false
        }
      }
      
      return {
        email,
        password,
        error,
        success,
        loading,
        submitted,
        onSubmit
      }
    }
  }
  </script>
  
  <style lang="scss" scoped>
  .login-container {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: calc(100vh - 150px);
  }
  
  .login-card {
    width: 100%;
    max-width: 500px;
    padding: 2rem;
    background-color: #fff;
    border-radius: 0.5rem;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    
    h2 {
      margin-bottom: 1.5rem;
      text-align: center;
      color: #007bff;
    }
  }
  
  .form-group {
    margin-bottom: 1rem;
    
    label {
      display: block;
      margin-bottom: 0.5rem;
      font-weight: 600;
    }
    
    .form-control {
      width: 100%;
      padding: 0.375rem 0.75rem;
      font-size: 1rem;
      line-height: 1.5;
      color: #495057;
      background-color: #fff;
      background-clip: padding-box;
      border: 1px solid #ced4da;
      border-radius: 0.25rem;
      transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
      
      &:focus {
        color: #495057;
        background-color: #fff;
        border-color: #80bdff;
        outline: 0;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
      }
      
      &.is-invalid {
        border-color: #dc3545;
        
        &:focus {
          box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
        }
      }
    }
    
    .invalid-feedback {
      display: block;
      width: 100%;
      margin-top: 0.25rem;
      font-size: 80%;
      color: #dc3545;
    }
  }
  
  .form-actions {
    margin-top: 1.5rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    
    button {
      width: 100%;
      margin-bottom: 1rem;
    }
  }
  </style>
